production:
  adapter: sqlserver
  mode: dblib
  host: SQL05VS03
  port: 1882
  username: GESLICOUSER
  password: SQLCDR
  encoding: utf8

development:
  adapter: sqlserver
  mode: dblib
  host: pe1950-15
  username: GESLICOUSER
  password: SARA1512
  encoding: utf8

test:
  adapter: sqlserver
  mode: dblib
  host: pe1950-15
  username: GESLICOUSER
  password: SARA1512
  encoding: utf8