production:
  adapter: sqlserver
  mode: dblib
  host: SQL12VS02
  port: 55916
  username: GESLICOUSER
  password: SQLCDR
  encoding: utf8

development:
  adapter: sqlserver
  mode: dblib
  host: SQL12DESA01
  port: 1433
  username: GESLICOUSER
  password: SQLCDR
  encoding: utf8

test:
  adapter: sqlserver
  mode: dblib
  host: SQL12PRE01
  port: 1433
  username: GESLICOUSER
  password: SQLCDR
  encoding: utf8